CONNECTION_MSG_TYPE = "CONNECTION"
CONNECTION_MSG = lambda val : {
    "MSG_TYPE": CONNECTION_MSG_TYPE,
    "VALUE": val
}

GAME_ASSIGNED_MSG_TYPE = "GAME_ASSIGNED"
GAME_ASSIGNED_MSG = lambda val : {
    "MSG_TYPE": GAME_ASSIGNED_MSG_TYPE,
    "VALUE": val
}

STATUS_MSG_TYPE = "STATUS"
STATUS_MSG = lambda val : {
    "MSG_TYPE": STATUS_MSG_TYPE,
    "VALUE": val
}

REQUEST_STATUS_MSG_TYPE = "REQUEST_STATUS"
REQUEST_STATUS_MSG = {
    "MSG_TYPE": REQUEST_STATUS_MSG_TYPE,
    "VALUE": True
}


DISCONNECT_MSG_TYPE = "DISCONNECT"
DISCONNECT_MSG = {
    "MSG_TYPE": DISCONNECT_MSG_TYPE,
    "VALUE": True
}


START_CHATTING_PHASE_MSG_TYPE = "START_CHATTING_PHASE"
START_CHATTING_PHASE_MSG = {
    "MSG_TYPE": START_CHATTING_PHASE_MSG_TYPE,
    "VALUE": True
}

END_CHATTING_PHASE_MSG_TYPE = "END_CHATTING_PHASE"
END_CHATTING_PHASE_MSG = {
    "MSG_TYPE": END_CHATTING_PHASE_MSG_TYPE,
    "VALUE": True
}



CHAT_MSG_TYPE = "CHAT_MSG"
CHAT_MSG = lambda val : {
    "MSG_TYPE": CHAT_MSG_TYPE,
    "VALUE": val
}